### ISSUE TITLE
it has some h5py issue when installing tensorflow

### ISSUE THREAD

**Issue by jxr041100** [quic/sample-apps-for-robotics-platforms#47]
```
loot@qrb5165-rb5:/data# pip install tensorflow-1.13.1-cp27-none-linux_aarch64.whl
Processing ./tensorflow-1.13.1-cp27-none-linux_aarch64.whl
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: absl-py>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: wheel in /usr/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: enum34>=1.1.6 in /usr/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Collecting keras-applications>=1.0.6 (from tensorflow==1.13.1)
Requirement already satisfied: mock>=2.0.0 in /usr/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.13.1)
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/bb/48/13f49fc3fa0fdf916aa1419013bb8f2ad09674c275b4046d5ee669a46873/tensorflow_estimator-1.13.0-py2.py3-none-any.whl
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
Requirement already satisfied: futures>=3.1.1; python_version < "3" in /usr/lib/python2.7/dist-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python2.7/dist-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
Collecting h5py (from keras-applications>=1.0.6->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/5f/97/a58afbcf40e8abecededd9512978b4e4915374e5b80049af082f49cebe9a/h5py-2.10.0.tar.gz
Requirement already satisfied: setuptools>=36 in /usr/lib/python2.7/dist-packages (from markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
Building wheels for collected packages: h5py
  Running setup.py bdist_wheel for h5py ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Bsv076/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqHHmSDpip-wheel- --python-tag cp27:
    File "build/bdist.linux-aarch64/egg/pkgconfig/pkgconfig.py", line 281
      flags = _query(packages, *os_opts, *_build_options(option, static=static))
                                         ^
  SyntaxError: invalid syntax
  
  zip_safe flag not set; analyzing archive contents...
  
  Installed /tmp/pip-build-Bsv076/h5py/.eggs/pkgconfig-1.5.5-py2.7.egg
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-2.7
  creating build/lib.linux-aarch64-2.7/h5py
  copying h5py/__init__.py -> build/lib.linux-aarch64-2.7/h5py
  copying h5py/h5py_warnings.py -> build/lib.linux-aarch64-2.7/h5py
  copying h5py/highlevel.py -> build/lib.linux-aarch64-2.7/h5py
  copying h5py/ipy_completer.py -> build/lib.linux-aarch64-2.7/h5py
  copying h5py/version.py -> build/lib.linux-aarch64-2.7/h5py
  creating build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/compat.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  copying h5py/_hl/vds.py -> build/lib.linux-aarch64-2.7/h5py/_hl
  creating build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/common.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_attribute_create.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_attrs.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_attrs_data.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_base.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_completions.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dataset.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_datatype.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_deprecation.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dimension_scales.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_dtype.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_file.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_file2.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_file_image.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_filters.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_group.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5f.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5p.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5pl.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_h5t.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_objects.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_selections.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_slicing.py -> build/lib.linux-aarch64-2.7/h5py/tests
  copying h5py/tests/test_threads.py -> build/lib.linux-aarch64-2.7/h5py/tests
  creating build/lib.linux-aarch64-2.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Bsv076/h5py/setup.py", line 159, in <module>
      cmdclass = CMDCLASS,
    File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "setup_build.py", line 166, in run
      config.run()
    File "setup_configure.py", line 160, in run
      self.hdf5_version = autodetect_version(self.hdf5)
    File "setup_configure.py", line 196, in autodetect_version
      import pkgconfig
    File "build/bdist.linux-aarch64/egg/pkgconfig/__init__.py", line 1, in <module>
    File "/tmp/pip-build-Bsv076/h5py/.eggs/pkgconfig-1.5.5-py2.7.egg/pkgconfig/pkgconfig.py", line 281
      flags = _query(packages, *os_opts, *_build_options(option, static=static))
                                         ^
  SyntaxError: invalid syntax
  
  ----------------------------------------
  Failed building wheel for h5py
  Running setup.py clean for h5py
Failed to build h5py
Installing collected packages: h5py, keras-applications, tensorflow-estimator, tensorflow
  Running setup.py install for h5py ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Bsv076/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k5ue6t-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-2.7
    creating build/lib.linux-aarch64-2.7/h5py
    copying h5py/__init__.py -> build/lib.linux-aarch64-2.7/h5py
    copying h5py/h5py_warnings.py -> build/lib.linux-aarch64-2.7/h5py
    copying h5py/highlevel.py -> build/lib.linux-aarch64-2.7/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-aarch64-2.7/h5py
    copying h5py/version.py -> build/lib.linux-aarch64-2.7/h5py
    creating build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/compat.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    copying h5py/_hl/vds.py -> build/lib.linux-aarch64-2.7/h5py/_hl
    creating build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_attribute_create.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_attrs.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_attrs_data.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_base.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_completions.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dataset.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_datatype.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_deprecation.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dimension_scales.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_dtype.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_file.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_file2.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_file_image.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_filters.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_group.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5f.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5p.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5pl.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_h5t.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_objects.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_selections.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_slicing.py -> build/lib.linux-aarch64-2.7/h5py/tests
    copying h5py/tests/test_threads.py -> build/lib.linux-aarch64-2.7/h5py/tests
    creating build/lib.linux-aarch64-2.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/__init__.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
    copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-aarch64-2.7/h5py/tests/test_vds
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Bsv076/h5py/setup.py", line 159, in <module>
        cmdclass = CMDCLASS,
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setup_build.py", line 166, in run
        config.run()
      File "setup_configure.py", line 160, in run
        self.hdf5_version = autodetect_version(self.hdf5)
      File "setup_configure.py", line 196, in autodetect_version
        import pkgconfig
      File "build/bdist.linux-aarch64/egg/pkgconfig/__init__.py", line 1, in <module>
      File "/tmp/pip-build-Bsv076/h5py/.eggs/pkgconfig-1.5.5-py2.7.egg/pkgconfig/pkgconfig.py", line 281
        flags = _query(packages, *os_opts, *_build_options(option, static=static))
                                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Bsv076/h5py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k5ue6t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Bsv076/h5py/
root@qrb5165-rb5:/data# 
```

**Comment by jxr041100** [comment]
I found one solution to address the above problem:
``` apt install python-h5py```

**Comment by TUT-jiayou** [comment]
@XW-HKU  Hi, 
How to got the tensorflow python whl package? python3 also support?
